name: timecapsule
description: A secure geolocation-based notes application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  latlong2: 0.9.1
  geolocator: ^10.0.0
  flutter_map: ^5.0.0
  encrypt: ^5.0.1
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  file_picker: ^6.0.0
  flutter_local_notifications: ^17.2.1
  video_player: ^2.10.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
